services:
#  order.api:
#    image: order-api
#    build:
#      context: .
#      dockerfile: Order.API/Dockerfile
  order-mongodb:
    image: mongo:latest
    container_name: order-mongodb
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_DATABASE=Order
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container: