services:
  product-api:
    image: product.api
    build:
      context: .
      dockerfile: Product.API/Dockerfile
      
  product-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lfybbk1999
      POSTGRES_DB: productDB
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
