// <auto-generated />
using System;
using Inventory.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.API.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.API.Model.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74809422-51c1-4898-8dd9-e23c9f07edc2"),
                            Count = 200,
                            Name = "Картошка",
                            Price = 40m,
                            ProductId = new Guid("3aa8cc33-47da-4b19-bf36-6a6429244e7e")
                        },
                        new
                        {
                            Id = new Guid("d5ee9a45-c2f2-471e-bf45-bf38fde3d8aa"),
                            Count = 300,
                            Name = "Марковка",
                            Price = 35m,
                            ProductId = new Guid("ef798709-fc38-41fd-a262-61117b1ab91f")
                        },
                        new
                        {
                            Id = new Guid("be940514-8207-4041-9dd6-f17b98c7aa8c"),
                            Count = 500,
                            Name = "Вода",
                            Price = 80m,
                            ProductId = new Guid("23cb36d8-ea5f-42f8-badd-ffa6ce6d62c2")
                        },
                        new
                        {
                            Id = new Guid("d2c56805-ac08-48c6-bd99-ea53e14d6a7e"),
                            Count = 600,
                            Name = "Хлеб белый",
                            Price = 50m,
                            ProductId = new Guid("733d1ce3-cb68-441c-8640-31bfca4a6c50")
                        },
                        new
                        {
                            Id = new Guid("31115785-e806-44e5-8929-6426652d4913"),
                            Count = 300,
                            Name = "Хлеб чёрный",
                            Price = 50m,
                            ProductId = new Guid("c339a5e3-bcc9-4cad-b128-96016fccf794")
                        },
                        new
                        {
                            Id = new Guid("07626fad-9ce0-4d63-b1db-88fea9c76cb6"),
                            Count = 250,
                            Name = "Пельмени",
                            Price = 200m,
                            ProductId = new Guid("13941b7c-1ceb-4d02-96b1-ba2571c6671a")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
