services:
#  notification-api:
#    image: notification.api
#    build:
#      context: .
#      dockerfile: Notification.API/Dockerfile
  notofication-mongodb:
    image: mongo:latest
    container_name: notification-mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=Notification
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data_container:/data/db
  
  notification-mq:
    image: rabbitmq:management
    container_name: Microservices.RabbitMq
    hostname: microservices-m
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
        
volumes:
  mongodb_data_container: